[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = "1"
serde = { version = "1", features = ["derive"] }


[[bin]]
name = "day01"
path = "src/day01.rs"


[profile.release]
debug = true
