[package]
name = "aoc2021"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = "3.0.0-beta.5"
anyhow = "1"
itertools = "0.10"


[[bin]]
name = "day01"
path = "src/day01.rs"


[profile.release]
debug = true
